/**
 * Catalogue des aéroports canadiens — 445 entrées.
 *
 * GÉNÉRÉ AUTOMATIQUEMENT — ne pas éditer à la main.
 * Régénérer avec : node scripts/import-airports.mjs
 *
 * Source : OurAirports (domaine public). Périmètre retenu : aérodromes
 * canadiens hors héliports, hydrobases et pistes fermées, disposant d'un
 * code IATA ou desservis par des vols réguliers.
 *
 * Les champs propres au déploiement Flow (nom d'usage, phase, sous-réseau,
 * transporteurs) sont maintenus dans OVERRIDES du script d'import.
 */
import type { Airport } from './canada'

export const AIRPORTS: Airport[] = [
  /* ── QC · 71 aéroports ─────────────────────────────── */
  { code: 'AKV', icao: 'CYKO', name: 'Akulivik', province: 'QC', size: 'small', scheduled: true, status: 'future', gps: { lat: 60.8186, lng: -78.1486 } },
  { code: 'YTF', icao: 'CYTF', name: 'Alma', province: 'QC', size: 'medium', status: 'future', gps: { lat: 48.5089, lng: -71.6419 } },
  { code: 'YEY', icao: 'CYEY', name: 'Amos', province: 'QC', size: 'medium', status: 'future', gps: { lat: 48.5639, lng: -78.2497 } },
  { code: 'YPJ', icao: 'CYLA', name: 'Aupaluk', province: 'QC', size: 'small', scheduled: true, status: 'future', gps: { lat: 59.2967, lng: -69.5997 } },
  { code: 'YBC', icao: 'CYBC', name: 'Baie-Comeau', province: 'QC', size: 'medium', scheduled: true, status: 'prospect', operatingRegion: 'Côte-Nord', carriers: ['Air Liaison', 'PAL Airlines'], gps: { lat: 49.1325, lng: -68.2044 } },
  { code: 'YVB', icao: 'CYVB', name: 'Bonaventure', province: 'QC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 48.0711, lng: -65.4603 } },
  { code: 'ZBM', icao: 'CZBM', name: 'Bromont', province: 'QC', size: 'medium', status: 'future', gps: { lat: 45.2908, lng: -72.7414 } },
  { code: 'YML', icao: 'CYML', name: 'Charlevoix', province: 'QC', size: 'medium', status: 'future', gps: { lat: 47.5975, lng: -70.2239 } },
  { code: 'YHR', icao: 'CYHR', name: 'Chevery', province: 'QC', size: 'small', scheduled: true, status: 'pilot', operatingRegion: 'Basse-Côte-Nord', carriers: ['CMA'], gps: { lat: 50.4683, lng: -59.6378 } },
  { code: 'YMT', icao: 'CYMT', name: 'Chibougamau', province: 'QC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 49.7719, lng: -74.5281 } },
  { code: 'YKU', icao: 'CSU2', name: 'Chisasibi', province: 'QC', size: 'small', scheduled: true, status: 'future', gps: { lat: 53.8056, lng: -78.9169 } },
  { code: 'ZKG', icao: 'CTK6', name: 'Côte-Nord-du-Golfe-du-Saint-Laurent', province: 'QC', size: 'small', status: 'future', gps: { lat: 50.1958, lng: -61.2658 } },
  { code: 'YDO', icao: 'CYDO', name: 'Dolbeau-Saint-Felicien', province: 'QC', size: 'medium', status: 'future', gps: { lat: 48.7785, lng: -72.375 } },
  { code: 'ZEM', icao: 'CZEM', name: 'Eastmain River', province: 'QC', size: 'small', scheduled: true, status: 'future', gps: { lat: 52.2264, lng: -78.5225 } },
  { code: 'YOI', name: 'Éléonore Mine', province: 'QC', size: 'small', status: 'future', gps: { lat: 52.2219, lng: -76.6119 } },
  { code: 'YFG', icao: 'CTU2', name: 'Fontanges', province: 'QC', size: 'small', status: 'future', gps: { lat: 54.5539, lng: -71.1733 } },
  { code: 'YFE', icao: 'CYFE', name: 'Forestville', province: 'QC', size: 'medium', status: 'future', gps: { lat: 48.7461, lng: -69.0972 } },
  { code: 'YGP', icao: 'CYGP', name: 'Gaspé', province: 'QC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 48.7749, lng: -64.4819 } },
  { code: 'YND', icao: 'CYND', name: 'Gatineau', province: 'QC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 45.5217, lng: -75.5636 } },
  { code: 'YGV', icao: 'CYGV', name: 'Havre-Saint-Pierre', province: 'QC', size: 'medium', scheduled: true, status: 'prospect', operatingRegion: 'Côte-Nord', carriers: ['CMA', 'Air Liaison'], gps: { lat: 50.2819, lng: -63.6114 } },
  { code: 'YPH', icao: 'CYPH', name: 'Inukjuak', province: 'QC', size: 'small', scheduled: true, status: 'future', gps: { lat: 58.4719, lng: -78.0769 } },
  { code: 'YIK', icao: 'CYIK', name: 'Ivujivik', province: 'QC', size: 'small', scheduled: true, status: 'future', gps: { lat: 62.4173, lng: -77.9253 } },
  { code: 'XGR', icao: 'CYLU', name: 'Kangiqsualujjuaq', province: 'QC', size: 'small', scheduled: true, status: 'future', gps: { lat: 58.7114, lng: -65.9928 } },
  { code: 'YWB', icao: 'CYKG', name: 'Kangiqsujuaq', province: 'QC', size: 'small', scheduled: true, status: 'future', gps: { lat: 61.5886, lng: -71.9294 } },
  { code: 'YKG', icao: 'CYAS', name: 'Kangirsuk', province: 'QC', size: 'small', scheduled: true, status: 'future', gps: { lat: 60.0272, lng: -69.9992 } },
  { code: 'YAU', icao: 'CTP9', name: 'Kattiniq', province: 'QC', size: 'small', status: 'future', gps: { lat: 61.6622, lng: -73.3214 } },
  { code: 'YVP', icao: 'CYVP', name: 'Kuujjuaq', province: 'QC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 58.0961, lng: -68.4269 } },
  { code: 'YGW', icao: 'CYGW', name: 'Kuujjuarapik', province: 'QC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 55.2819, lng: -77.7653 } },
  { code: 'YGL', icao: 'CYGL', name: 'La Grande Rivière', province: 'QC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 53.6253, lng: -77.7042 } },
  { code: 'YAR', icao: 'CYAD', name: 'La Grande-3', province: 'QC', size: 'small', status: 'future', gps: { lat: 53.5717, lng: -76.1964 } },
  { code: 'YAH', icao: 'CYAH', name: 'La Grande-4', province: 'QC', size: 'medium', status: 'future', gps: { lat: 53.7547, lng: -73.6753 } },
  { code: 'YTM', icao: 'CYFJ', name: 'La Macaza', province: 'QC', size: 'medium', status: 'future', gps: { lat: 46.4094, lng: -74.78 } },
  { code: 'ZGS', icao: 'CTT5', name: 'La Romaine', province: 'QC', size: 'small', scheduled: true, status: 'pilot', operatingRegion: 'Basse-Côte-Nord', carriers: ['CMA'], gps: { lat: 50.2596, lng: -60.6744 } },
  { code: 'SSQ', icao: 'CSR8', name: 'La Sarre', province: 'QC', size: 'small', status: 'future', gps: { lat: 48.9172, lng: -79.1786 } },
  { code: 'ZLT', icao: 'CTU5', name: 'La Tabatière', province: 'QC', size: 'small', scheduled: true, status: 'future', gps: { lat: 50.8308, lng: -58.9756 } },
  { code: 'YLQ', icao: 'CYLQ', name: 'La Tuque', province: 'QC', size: 'small', status: 'future', gps: { lat: 47.4097, lng: -72.7889 } },
  { code: 'YLS', icao: 'CSH4', name: 'Lebel-sur-Quévillon', province: 'QC', size: 'small', status: 'future', gps: { lat: 49.0303, lng: -77.0172 } },
  { code: 'YGR', icao: 'CYGR', name: 'Les Îles-de-la-Madeleine', province: 'QC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 47.4252, lng: -61.7786 } },
  { code: 'YLP', name: 'Longue-Pointe-de-Mingan', province: 'QC', size: 'small', status: 'future', gps: { lat: 50.2869, lng: -64.1528 } },
  { code: 'YBX', icao: 'CYBX', name: 'Lourdes-de-Blanc-Sablon', province: 'QC', size: 'medium', scheduled: true, status: 'live', operatingRegion: 'Basse-Côte-Nord', carriers: ['CMA', 'PAL Airlines', 'Air Borealis'], gps: { lat: 51.4436, lng: -57.1853 }, highTraffic: true },
  { code: 'YNM', icao: 'CYNM', name: 'Matagami', province: 'QC', size: 'medium', status: 'future', gps: { lat: 49.7617, lng: -77.8028 } },
  { code: 'YME', icao: 'CYME', name: 'Matane', province: 'QC', size: 'medium', status: 'future', gps: { lat: 48.8569, lng: -67.4533 } },
  { code: 'YMW', icao: 'CYMW', name: 'Messines', province: 'QC', size: 'small', status: 'future', gps: { lat: 46.2728, lng: -75.9906 } },
  { code: 'YYY', icao: 'CYYY', name: 'Mont-Joli', province: 'QC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 48.6086, lng: -68.2081 } },
  { code: 'YHU', icao: 'CYHU', name: 'Montréal', province: 'QC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 45.5175, lng: -73.4169 } },
  { code: 'YMX', icao: 'CYMX', name: 'Montréal', province: 'QC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 45.6795, lng: -74.0387 } },
  { code: 'YUL', icao: 'CYUL', name: 'Montréal-Trudeau (hub logistique)', province: 'QC', size: 'large', scheduled: true, status: 'live', operatingRegion: 'Hub', carriers: ['CMA', 'PAL Airlines', 'Air Liaison'], gps: { lat: 45.4678, lng: -73.7423 } },
  { code: 'YNA', icao: 'CYNA', name: 'Natashquan', province: 'QC', size: 'medium', scheduled: true, status: 'live', operatingRegion: 'Basse-Côte-Nord', carriers: ['CMA', 'Air Liaison'], gps: { lat: 50.1901, lng: -61.789 } },
  { code: 'YNS', icao: 'CYHH', name: 'Nemiscau', province: 'QC', size: 'small', scheduled: true, status: 'future', gps: { lat: 51.6911, lng: -76.1356 } },
  { code: 'YPN', icao: 'CYPN', name: 'Port-Menier (Anticosti)', province: 'QC', size: 'medium', scheduled: true, status: 'prospect', operatingRegion: 'Côte-Nord', carriers: ['Air Liaison'], gps: { lat: 49.8364, lng: -64.2886 } },
  { code: 'YPX', icao: 'CYPX', name: 'Puvirnituq', province: 'QC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 60.0506, lng: -77.2869 } },
  { code: 'YQC', icao: 'CYHA', name: 'Quaqtaq', province: 'QC', size: 'small', scheduled: true, status: 'future', gps: { lat: 61.0464, lng: -69.6178 } },
  { code: 'YQB', icao: 'CYQB', name: 'Quebec', province: 'QC', size: 'large', scheduled: true, status: 'future', gps: { lat: 46.7911, lng: -71.3933 } },
  { code: 'YXK', icao: 'CYXK', name: 'Rimouski', province: 'QC', size: 'medium', status: 'future', gps: { lat: 48.4776, lng: -68.4963 } },
  { code: 'YRI', icao: 'CYRI', name: 'Rivière-du-Loup', province: 'QC', size: 'medium', status: 'future', gps: { lat: 47.7644, lng: -69.5847 } },
  { code: 'YRJ', icao: 'CYRJ', name: 'Roberval', province: 'QC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 48.5197, lng: -72.2657 } },
  { code: 'YUY', icao: 'CYUY', name: 'Rouyn-Noranda', province: 'QC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 48.2061, lng: -78.8356 } },
  { code: 'YBG', icao: 'CYBG', name: 'Saguenay', province: 'QC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 48.3301, lng: -70.992 } },
  { code: 'YIF', icao: 'CYIF', name: 'Saint-Augustin', province: 'QC', size: 'medium', scheduled: true, status: 'live', operatingRegion: 'Basse-Côte-Nord', carriers: ['CMA'], gps: { lat: 51.2117, lng: -58.6583 } },
  { code: 'YZG', icao: 'CYZG', name: 'Salluit', province: 'QC', size: 'small', scheduled: true, status: 'future', gps: { lat: 62.1794, lng: -75.6672 } },
  { code: 'YKL', icao: 'CYKL', name: 'Schefferville', province: 'QC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 54.8053, lng: -66.8053 } },
  { code: 'YZV', icao: 'CYZV', name: 'Sept-Îles', province: 'QC', size: 'medium', scheduled: true, status: 'prospect', operatingRegion: 'Côte-Nord', carriers: ['CMA', 'Air Liaison', 'PAL Airlines'], gps: { lat: 50.2233, lng: -66.2656 }, highTraffic: true },
  { code: 'YSC', icao: 'CYSC', name: 'Sherbrooke', province: 'QC', size: 'medium', status: 'future', gps: { lat: 45.4386, lng: -71.6914 } },
  { code: 'YJN', icao: 'CYJN', name: 'St Jean', province: 'QC', size: 'medium', status: 'future', gps: { lat: 45.2944, lng: -73.2811 } },
  { code: 'YTQ', icao: 'CYTQ', name: 'Tasiujaq', province: 'QC', size: 'small', scheduled: true, status: 'future', gps: { lat: 58.6678, lng: -69.9558 } },
  { code: 'ZTB', icao: 'CTB6', name: 'Tête-à-la-Baleine', province: 'QC', size: 'small', scheduled: true, status: 'pilot', operatingRegion: 'Basse-Côte-Nord', carriers: ['CMA'], gps: { lat: 50.6744, lng: -59.3836 } },
  { code: 'YRQ', icao: 'CYRQ', name: 'Trois-Rivières', province: 'QC', size: 'medium', status: 'future', gps: { lat: 46.3528, lng: -72.6794 } },
  { code: 'YUD', icao: 'CYMU', name: 'Umiujaq', province: 'QC', size: 'small', scheduled: true, status: 'future', gps: { lat: 56.5361, lng: -76.5183 } },
  { code: 'YVO', icao: 'CYVO', name: 'Val-d\'Or', province: 'QC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 48.0533, lng: -77.7828 } },
  { code: 'YKQ', icao: 'CYKQ', name: 'Waskaganish', province: 'QC', size: 'small', scheduled: true, status: 'future', gps: { lat: 51.4733, lng: -78.7583 } },
  { code: 'YNC', icao: 'CYNC', name: 'Wemindji', province: 'QC', size: 'small', scheduled: true, status: 'future', gps: { lat: 53.0106, lng: -78.8311 } },

  /* ── NL · 22 aéroports ─────────────────────────────── */
  { code: 'YBI', icao: 'CCE4', name: 'Black Tickle', province: 'NL', size: 'small', scheduled: true, status: 'future', gps: { lat: 53.4698, lng: -55.7875 } },
  { code: 'YRF', icao: 'CYCA', name: 'Cartwright', province: 'NL', size: 'small', scheduled: true, status: 'future', gps: { lat: 53.6825, lng: -57.0423 } },
  { code: 'YHG', icao: 'CCH4', name: 'Charlottetown', province: 'NL', size: 'small', scheduled: true, status: 'future', gps: { lat: 52.7658, lng: -56.1124 } },
  { code: 'ZUM', icao: 'CZUM', name: 'Churchill Falls', province: 'NL', size: 'small', scheduled: true, status: 'future', gps: { lat: 53.5619, lng: -64.1064 } },
  { code: 'YDF', icao: 'CYDF', name: 'Deer Lake', province: 'NL', size: 'medium', scheduled: true, status: 'future', gps: { lat: 49.2082, lng: -57.3961 } },
  { code: 'YQX', icao: 'CYQX', name: 'Gander', province: 'NL', size: 'medium', scheduled: true, status: 'future', gps: { lat: 48.9363, lng: -54.5677 } },
  { code: 'YYR', icao: 'CYYR', name: 'Happy Valley-Goose Bay', province: 'NL', size: 'medium', scheduled: true, status: 'prospect', operatingRegion: 'Labrador', carriers: ['PAL Airlines', 'Air Borealis'], gps: { lat: 53.3192, lng: -60.4258 }, highTraffic: true },
  { code: 'YHO', icao: 'CYHO', name: 'Hopedale', province: 'NL', size: 'small', scheduled: true, status: 'future', operatingRegion: 'Labrador', carriers: ['Air Borealis'], gps: { lat: 55.4488, lng: -60.2281 } },
  { code: 'YMN', icao: 'CYFT', name: 'Makkovik', province: 'NL', size: 'small', scheduled: true, status: 'future', gps: { lat: 55.0773, lng: -59.1879 } },
  { code: 'YMH', icao: 'CYMH', name: 'Mary\'s Harbour', province: 'NL', size: 'small', scheduled: true, status: 'future', gps: { lat: 52.3028, lng: -55.8474 } },
  { code: 'YDP', icao: 'CYDP', name: 'Nain', province: 'NL', size: 'small', scheduled: true, status: 'future', operatingRegion: 'Labrador', carriers: ['Air Borealis'], gps: { lat: 56.5508, lng: -61.6822 } },
  { code: 'YNP', icao: 'CNH2', name: 'Natuashish', province: 'NL', size: 'small', scheduled: true, status: 'future', gps: { lat: 55.9139, lng: -61.1844 } },
  { code: 'YHA', icao: 'CCP4', name: 'Port Hope Simpson', province: 'NL', size: 'small', scheduled: true, status: 'future', gps: { lat: 52.5281, lng: -56.2861 } },
  { code: 'YSO', icao: 'CCD4', name: 'Postville', province: 'NL', size: 'small', scheduled: true, status: 'future', gps: { lat: 54.9105, lng: -59.7851 } },
  { code: 'YRG', icao: 'CCZ2', name: 'Rigolet', province: 'NL', size: 'small', scheduled: true, status: 'future', operatingRegion: 'Labrador', carriers: ['Air Borealis'], gps: { lat: 54.1797, lng: -58.4575 } },
  { code: 'YSV', name: 'Saglek', province: 'NL', size: 'small', status: 'future', gps: { lat: 58.4743, lng: -62.654 } },
  { code: 'YAY', icao: 'CYAY', name: 'St. Anthony', province: 'NL', size: 'medium', scheduled: true, status: 'future', gps: { lat: 51.3919, lng: -56.0832 } },
  { code: 'YYT', icao: 'CYYT', name: 'St. John\'s', province: 'NL', size: 'large', scheduled: true, status: 'future', gps: { lat: 47.6186, lng: -52.7519 } },
  { code: 'YFX', icao: 'CCK4', name: 'St. Lewis', province: 'NL', size: 'small', scheduled: true, status: 'future', gps: { lat: 52.3728, lng: -55.6739 } },
  { code: 'YJT', icao: 'CYJT', name: 'Stephenville', province: 'NL', size: 'medium', status: 'future', gps: { lat: 48.5434, lng: -58.5529 } },
  { code: 'YWK', icao: 'CYWK', name: 'Wabush', province: 'NL', size: 'medium', scheduled: true, status: 'prospect', operatingRegion: 'Labrador', carriers: ['PAL Airlines'], gps: { lat: 52.9219, lng: -66.8644 } },
  { code: 'YWM', icao: 'CCA6', name: 'Williams Harbour', province: 'NL', size: 'small', scheduled: true, status: 'future', gps: { lat: 52.5674, lng: -55.7849 } },

  /* ── PE · 2 aéroports ─────────────────────────────── */
  { code: 'YYG', icao: 'CYYG', name: 'Charlottetown', province: 'PE', size: 'medium', scheduled: true, status: 'future', gps: { lat: 46.2889, lng: -63.1252 } },
  { code: 'YSU', icao: 'CYSU', name: 'Slemon Park', province: 'PE', size: 'medium', status: 'future', gps: { lat: 46.4406, lng: -63.8336 } },

  /* ── NS · 7 aéroports ─────────────────────────────── */
  { code: 'YDG', icao: 'CYID', name: 'Digby', province: 'NS', size: 'medium', status: 'future', gps: { lat: 44.5458, lng: -65.7854 } },
  { code: 'YZX', icao: 'CYZX', name: 'Greenwood', province: 'NS', size: 'medium', status: 'future', gps: { lat: 44.9844, lng: -64.9169 } },
  { code: 'YHZ', icao: 'CYHZ', name: 'Halifax', province: 'NS', size: 'large', scheduled: true, status: 'future', gps: { lat: 44.8808, lng: -63.5086 } },
  { code: 'YPS', icao: 'CYPD', name: 'Port Hawkesbury', province: 'NS', size: 'medium', status: 'future', gps: { lat: 45.6567, lng: -61.3681 } },
  { code: 'YSA', icao: 'CSB2', name: 'Sable Island', province: 'NS', size: 'small', status: 'future', gps: { lat: 43.9282, lng: -59.949 } },
  { code: 'YQY', icao: 'CYQY', name: 'Sydney', province: 'NS', size: 'medium', scheduled: true, status: 'future', gps: { lat: 46.1611, lng: -60.0498 } },
  { code: 'YQI', icao: 'CYQI', name: 'Yarmouth', province: 'NS', size: 'medium', status: 'future', gps: { lat: 43.8269, lng: -66.0881 } },

  /* ── NB · 7 aéroports ─────────────────────────────── */
  { code: 'YCL', icao: 'CYCL', name: 'Charlo', province: 'NB', size: 'medium', status: 'future', gps: { lat: 47.9908, lng: -66.3303 } },
  { code: 'YFC', icao: 'CYFC', name: 'Fredericton', province: 'NB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 45.8687, lng: -66.5299 } },
  { code: 'YCH', icao: 'CYCH', name: 'Miramichi', province: 'NB', size: 'medium', status: 'future', gps: { lat: 47.0078, lng: -65.4492 } },
  { code: 'YQM', icao: 'CYQM', name: 'Moncton', province: 'NB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 46.1132, lng: -64.6772 } },
  { code: 'YSJ', icao: 'CYSJ', name: 'Saint John', province: 'NB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 45.3161, lng: -65.8903 } },
  { code: 'YSL', icao: 'CYSL', name: 'Saint-Léonard', province: 'NB', size: 'medium', status: 'future', gps: { lat: 47.1571, lng: -67.8362 } },
  { code: 'ZBF', icao: 'CZBF', name: 'South Tetagouche', province: 'NB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 47.6297, lng: -65.7389 } },

  /* ── ON · 87 aéroports ─────────────────────────────── */
  { code: 'YAX', icao: 'CKB6', name: 'Angling Lake', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 53.8492, lng: -89.5794 } },
  { code: 'YYW', icao: 'CYYW', name: 'Armstrong', province: 'ON', size: 'medium', status: 'future', gps: { lat: 50.2903, lng: -88.9097 } },
  { code: 'YIB', icao: 'CYIB', name: 'Atikokan', province: 'ON', size: 'medium', status: 'future', gps: { lat: 48.7739, lng: -91.6386 } },
  { code: 'YAT', icao: 'CYAT', name: 'Attawapiskat', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 52.9275, lng: -82.4319 } },
  { code: 'YLK', icao: 'CYLS', name: 'Barrie', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 44.4851, lng: -79.5547 } },
  { code: 'XBE', icao: 'CNE3', name: 'Bearskin Lake', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 53.9656, lng: -91.0272 } },
  { code: 'YTL', icao: 'CYTL', name: 'Big Trout Lake', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 53.8178, lng: -89.8969 } },
  { code: 'YKF', icao: 'CYKF', name: 'Breslau', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 43.4608, lng: -80.3786 } },
  { code: 'XBR', icao: 'CNL3', name: 'Brockville', province: 'ON', size: 'small', status: 'future', gps: { lat: 44.6394, lng: -75.7503 } },
  { code: 'YAC', icao: 'CYAC', name: 'Cat Lake', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 51.7272, lng: -91.8244 } },
  { code: 'YLD', icao: 'CYLD', name: 'Chapleau', province: 'ON', size: 'medium', status: 'future', gps: { lat: 47.82, lng: -83.3467 } },
  { code: 'XCM', icao: 'CYCK', name: 'Chatham-Kent', province: 'ON', size: 'small', status: 'future', gps: { lat: 42.3064, lng: -82.0819 } },
  { code: 'YCN', icao: 'CYCN', name: 'Cochrane', province: 'ON', size: 'medium', status: 'future', gps: { lat: 49.1056, lng: -81.0136 } },
  { code: 'YCC', icao: 'CYCC', name: 'Cornwall', province: 'ON', size: 'medium', status: 'future', gps: { lat: 45.0926, lng: -74.5677 } },
  { code: 'YVZ', icao: 'CYVZ', name: 'Deer Lake', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 52.6556, lng: -94.0612 } },
  { code: 'YHD', icao: 'CYHD', name: 'Dryden', province: 'ON', size: 'medium', status: 'future', gps: { lat: 49.8317, lng: -92.7442 } },
  { code: 'YXR', icao: 'CYXR', name: 'Earlton', province: 'ON', size: 'medium', status: 'future', gps: { lat: 47.6974, lng: -79.8473 } },
  { code: 'YEB', icao: 'CPF2', name: 'Echo Bay', province: 'ON', size: 'small', status: 'future', gps: { lat: 46.4212, lng: -84.0965 } },
  { code: 'YEL', icao: 'CYEL', name: 'Elliot Lake', province: 'ON', size: 'medium', status: 'future', gps: { lat: 46.3514, lng: -82.5614 } },
  { code: 'YFA', icao: 'CYFA', name: 'Fort Albany', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 52.2035, lng: -81.6952 } },
  { code: 'YAG', icao: 'CYAG', name: 'Fort Frances', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 48.6557, lng: -93.4435 } },
  { code: 'YFH', icao: 'CYFH', name: 'Fort Hope', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 51.5619, lng: -87.9078 } },
  { code: 'YER', icao: 'CYER', name: 'Fort Severn', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 56.0189, lng: -87.6761 } },
  { code: 'YGQ', icao: 'CYGQ', name: 'Geraldton', province: 'ON', size: 'medium', status: 'future', gps: { lat: 49.7783, lng: -86.9394 } },
  { code: 'YZE', icao: 'CYZE', name: 'Gore Bay', province: 'ON', size: 'medium', status: 'future', gps: { lat: 45.8853, lng: -82.5678 } },
  { code: 'YQA', icao: 'CYQA', name: 'Gravenhurst', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 44.9754, lng: -79.3065 } },
  { code: 'YHM', icao: 'CYHM', name: 'Hamilton', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 43.1735, lng: -79.9312 } },
  { code: 'YHF', icao: 'CYHF', name: 'Hearst', province: 'ON', size: 'medium', status: 'future', gps: { lat: 49.7142, lng: -83.6861 } },
  { code: 'YHN', icao: 'CYHN', name: 'Hornepayne', province: 'ON', size: 'medium', status: 'future', gps: { lat: 49.1931, lng: -84.7589 } },
  { code: 'YCE', icao: 'CYCE', name: 'Huron Park', province: 'ON', size: 'medium', status: 'future', gps: { lat: 43.2856, lng: -81.5083 } },
  { code: 'ZUC', icao: 'CZUC', name: 'Ignace', province: 'ON', size: 'medium', status: 'future', gps: { lat: 49.4282, lng: -91.7204 } },
  { code: 'YYU', icao: 'CYYU', name: 'Kapuskasing', province: 'ON', size: 'medium', status: 'future', gps: { lat: 49.4116, lng: -82.4696 } },
  { code: 'XKS', icao: 'CYAQ', name: 'Kasabonika', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 53.5247, lng: -88.6428 } },
  { code: 'ZKE', icao: 'CZKE', name: 'Kashechewan', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 52.2825, lng: -81.6778 } },
  { code: 'KEW', icao: 'CPV8', name: 'Keewaywin', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 52.9911, lng: -92.8364 } },
  { code: 'YQK', icao: 'CYQK', name: 'Kenora', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 49.7883, lng: -94.3631 } },
  { code: 'YKD', icao: 'CYKM', name: 'Kincardine', province: 'ON', size: 'medium', status: 'future', gps: { lat: 44.2014, lng: -81.6067 } },
  { code: 'KIF', icao: 'CNM5', name: 'Kingfisher Lake', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 53.0125, lng: -89.8553 } },
  { code: 'YGK', icao: 'CYGK', name: 'Kingston', province: 'ON', size: 'medium', status: 'future', gps: { lat: 44.2253, lng: -76.5969 } },
  { code: 'YKX', icao: 'CYKX', name: 'Kirkland Lake', province: 'ON', size: 'medium', status: 'future', gps: { lat: 48.2103, lng: -79.9814 } },
  { code: 'YLH', icao: 'CYLH', name: 'Lansdowne House', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 52.1956, lng: -87.9342 } },
  { code: 'YXU', icao: 'CYXU', name: 'London', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 43.0328, lng: -81.149 } },
  { code: 'YMG', icao: 'CYMG', name: 'Manitouwadge', province: 'ON', size: 'medium', status: 'future', gps: { lat: 49.0839, lng: -85.8606 } },
  { code: 'YSP', icao: 'CYSP', name: 'Marathon', province: 'ON', size: 'medium', status: 'future', gps: { lat: 48.7553, lng: -86.3444 } },
  { code: 'YMO', icao: 'CYMO', name: 'Moosonee', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 51.2911, lng: -80.6078 } },
  { code: 'MSA', icao: 'CZMD', name: 'Muskrat Dam', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 53.4414, lng: -91.7628 } },
  { code: 'YQN', icao: 'CYQN', name: 'Nakina', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 50.1828, lng: -86.6964 } },
  { code: 'YCM', icao: 'CYSN', name: 'Niagara-on-the-Lake', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 43.1916, lng: -79.1717 } },
  { code: 'YYB', icao: 'CYYB', name: 'North Bay', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 46.3636, lng: -79.4228 } },
  { code: 'YNO', icao: 'CKQ3', name: 'North Spirit Lake', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 52.49, lng: -92.9711 } },
  { code: 'YOG', icao: 'CYKP', name: 'Ogoki Post', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 51.6586, lng: -85.9017 } },
  { code: 'YBS', icao: 'CKM8', name: 'Opapimiskan Lake', province: 'ON', size: 'small', status: 'future', gps: { lat: 52.6067, lng: -90.3769 } },
  { code: 'YOO', icao: 'CYOO', name: 'Oshawa', province: 'ON', size: 'medium', status: 'future', gps: { lat: 43.9228, lng: -78.895 } },
  { code: 'YOW', icao: 'CYOW', name: 'Ottawa', province: 'ON', size: 'large', scheduled: true, status: 'future', gps: { lat: 45.3225, lng: -75.6692 } },
  { code: 'YRO', icao: 'CYRO', name: 'Ottawa', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 45.4605, lng: -75.644 } },
  { code: 'YOS', icao: 'CYOS', name: 'Owen Sound', province: 'ON', size: 'medium', status: 'future', gps: { lat: 44.5903, lng: -80.8375 } },
  { code: 'YPD', icao: 'CNK4', name: 'Parry Sound', province: 'ON', size: 'small', status: 'future', gps: { lat: 45.2575, lng: -79.8297 } },
  { code: 'YPO', icao: 'CYPO', name: 'Peawanuck', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 54.9879, lng: -85.4426 } },
  { code: 'CYPT', icao: 'CYPT', name: 'Pelee Island', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 41.778, lng: -82.6742 } },
  { code: 'YTA', icao: 'CYTA', name: 'Pembroke', province: 'ON', size: 'medium', status: 'future', gps: { lat: 45.8644, lng: -77.2517 } },
  { code: 'YPQ', icao: 'CYPQ', name: 'Peterborough', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 44.2323, lng: -78.3621 } },
  { code: 'YPL', icao: 'CYPL', name: 'Pickle Lake', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 51.4464, lng: -90.2142 } },
  { code: 'YPM', icao: 'CYPM', name: 'Pikangikum', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 51.8197, lng: -93.9733 } },
  { code: 'YHP', icao: 'CYHP', name: 'Poplar Hill', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 52.1133, lng: -94.2556 } },
  { code: 'YRL', icao: 'CYRL', name: 'Red Lake', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 51.0669, lng: -93.7931 } },
  { code: 'ZRJ', icao: 'CZRJ', name: 'Round Lake', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 52.9436, lng: -91.3128 } },
  { code: 'ZPB', icao: 'CZPB', name: 'Sachigo Lake', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 53.8909, lng: -92.1959 } },
  { code: 'ZSJ', icao: 'CZSJ', name: 'Sandy Lake', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 53.0642, lng: -93.3444 } },
  { code: 'YZR', icao: 'CYZR', name: 'Sarnia', province: 'ON', size: 'medium', status: 'future', gps: { lat: 42.9994, lng: -82.3089 } },
  { code: 'YAM', icao: 'CYAM', name: 'Sault Ste Marie', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 46.4832, lng: -84.5085 } },
  { code: 'YEM', icao: 'CYEM', name: 'Sheguiandah', province: 'ON', size: 'medium', status: 'future', gps: { lat: 45.8424, lng: -81.8576 } },
  { code: 'YXL', icao: 'CYXL', name: 'Sioux Lookout', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 50.1139, lng: -91.9053 } },
  { code: 'CKD9', icao: 'CKD9', name: 'Slate Falls', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 51.13, lng: -91.6656 } },
  { code: 'YSH', icao: 'CYSH', name: 'Smiths Falls', province: 'ON', size: 'medium', status: 'future', gps: { lat: 44.9458, lng: -75.9406 } },
  { code: 'YQS', icao: 'CYQS', name: 'St Thomas', province: 'ON', size: 'medium', status: 'future', gps: { lat: 42.77, lng: -81.1108 } },
  { code: 'YSB', icao: 'CYSB', name: 'Sudbury', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 46.625, lng: -80.7989 } },
  { code: 'SUR', icao: 'CJV7', name: 'Summer Beaver', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 52.7086, lng: -88.5419 } },
  { code: 'YQT', icao: 'CYQT', name: 'Thunder Bay', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 48.3719, lng: -89.3239 } },
  { code: 'YTS', icao: 'CYTS', name: 'Timmins', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 48.5697, lng: -81.3767 } },
  { code: 'YTZ', icao: 'CYTZ', name: 'Toronto', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 43.6279, lng: -79.3955 } },
  { code: 'YYZ', icao: 'CYYZ', name: 'Toronto', province: 'ON', size: 'large', scheduled: true, status: 'future', gps: { lat: 43.6759, lng: -79.6294 } },
  { code: 'YTR', icao: 'CYTR', name: 'Trenton', province: 'ON', size: 'medium', status: 'future', gps: { lat: 44.1189, lng: -77.5281 } },
  { code: 'YXZ', icao: 'CYXZ', name: 'Wawa', province: 'ON', size: 'medium', status: 'future', gps: { lat: 47.9667, lng: -84.7867 } },
  { code: 'YWP', icao: 'CYWP', name: 'Webequie', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 52.9594, lng: -87.3749 } },
  { code: 'YVV', icao: 'CYVV', name: 'Wiarton', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 44.7458, lng: -81.1072 } },
  { code: 'YQG', icao: 'CYQG', name: 'Windsor', province: 'ON', size: 'medium', scheduled: true, status: 'future', gps: { lat: 42.2756, lng: -82.9556 } },
  { code: 'WNN', icao: 'CKL3', name: 'Wunnumin Lake', province: 'ON', size: 'small', scheduled: true, status: 'future', gps: { lat: 52.8939, lng: -89.2892 } },

  /* ── MB · 42 aéroports ─────────────────────────────── */
  { code: 'YBV', icao: 'CYBV', name: 'Berens River', province: 'MB', size: 'small', scheduled: true, status: 'future', gps: { lat: 52.3589, lng: -97.0183 } },
  { code: 'YDV', icao: 'CZTA', name: 'Bloodvein River', province: 'MB', size: 'small', scheduled: true, status: 'future', gps: { lat: 51.7846, lng: -96.6923 } },
  { code: 'YBR', icao: 'CYBR', name: 'Brandon', province: 'MB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 49.91, lng: -99.9519 } },
  { code: 'YBT', icao: 'CYBT', name: 'Brochet', province: 'MB', size: 'small', scheduled: true, status: 'future', gps: { lat: 57.8894, lng: -101.679 } },
  { code: 'YYQ', icao: 'CYYQ', name: 'Churchill', province: 'MB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 58.7392, lng: -94.065 } },
  { code: 'YCR', icao: 'CYCR', name: 'Cross Lake', province: 'MB', size: 'small', scheduled: true, status: 'future', gps: { lat: 54.6098, lng: -97.7624 } },
  { code: 'YDN', icao: 'CYDN', name: 'Dauphin', province: 'MB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 51.1008, lng: -100.052 } },
  { code: 'YFO', icao: 'CYFO', name: 'Flin Flon', province: 'MB', size: 'small', scheduled: true, status: 'future', gps: { lat: 54.6781, lng: -101.682 } },
  { code: 'YGX', icao: 'CYGX', name: 'Gillam', province: 'MB', size: 'small', scheduled: true, status: 'future', gps: { lat: 56.3571, lng: -94.7115 } },
  { code: 'YGM', icao: 'CYGM', name: 'Gimli', province: 'MB', size: 'medium', status: 'future', gps: { lat: 50.6281, lng: -97.0433 } },
  { code: 'CJB6', icao: 'CJB6', name: 'Gods Lake', province: 'MB', size: 'small', scheduled: true, status: 'future', gps: { lat: 54.7805, lng: -93.7182 } },
  { code: 'YGO', icao: 'CYGO', name: 'Gods Lake Narrows', province: 'MB', size: 'small', scheduled: true, status: 'future', gps: { lat: 54.5577, lng: -94.4901 } },
  { code: 'ZGI', icao: 'CZGI', name: 'Gods River', province: 'MB', size: 'small', scheduled: true, status: 'future', gps: { lat: 54.8397, lng: -94.0786 } },
  { code: 'ILF', icao: 'CZBD', name: 'Ilford', province: 'MB', size: 'small', scheduled: true, status: 'future', gps: { lat: 56.0516, lng: -95.6188 } },
  { code: 'YIV', icao: 'CYIV', name: 'Island Lake', province: 'MB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 53.8572, lng: -94.6536 } },
  { code: 'ZJG', icao: 'CZJG', name: 'Jenpeg', province: 'MB', size: 'medium', status: 'future', gps: { lat: 54.5189, lng: -98.0461 } },
  { code: 'KES', icao: 'CZEE', name: 'Kelsey', province: 'MB', size: 'medium', status: 'future', gps: { lat: 56.0375, lng: -96.5097 } },
  { code: 'YKE', icao: 'CJT3', name: 'Knee Lake', province: 'MB', size: 'small', status: 'future', gps: { lat: 54.9153, lng: -94.7981 } },
  { code: 'XLB', icao: 'CZWH', name: 'Lac Brochet', province: 'MB', size: 'small', scheduled: true, status: 'future', gps: { lat: 58.6143, lng: -101.469 } },
  { code: 'CYAX', icao: 'CYAX', name: 'Lac du Bonnet', province: 'MB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 50.2944, lng: -96.01 } },
  { code: 'LRQ', icao: 'CJC8', name: 'Laurie River', province: 'MB', size: 'small', status: 'future', gps: { lat: 56.2486, lng: -101.304 } },
  { code: 'YLR', icao: 'CYLR', name: 'Leaf Rapids', province: 'MB', size: 'medium', status: 'future', gps: { lat: 56.5133, lng: -99.9853 } },
  { code: 'ZGR', icao: 'CZGR', name: 'Little Grand Rapids', province: 'MB', size: 'small', status: 'future', gps: { lat: 52.0454, lng: -95.4662 } },
  { code: 'YYL', icao: 'CYYL', name: 'Lynn Lake', province: 'MB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 56.8639, lng: -101.076 } },
  { code: 'YNE', icao: 'CYNE', name: 'Norway House', province: 'MB', size: 'small', scheduled: true, status: 'future', gps: { lat: 53.9583, lng: -97.8442 } },
  { code: 'YOH', icao: 'CYOH', name: 'Oxford House', province: 'MB', size: 'small', scheduled: true, status: 'future', gps: { lat: 54.9333, lng: -95.2789 } },
  { code: 'PIW', icao: 'CZMN', name: 'Pikwitonei', province: 'MB', size: 'medium', status: 'future', gps: { lat: 55.5889, lng: -97.1642 } },
  { code: 'XPP', icao: 'CZNG', name: 'Poplar River', province: 'MB', size: 'small', status: 'future', gps: { lat: 52.9965, lng: -97.2742 } },
  { code: 'YPG', icao: 'CYPG', name: 'Portage la Prairie', province: 'MB', size: 'medium', status: 'future', gps: { lat: 49.9031, lng: -98.2738 } },
  { code: 'XPK', icao: 'CZFG', name: 'Pukatawagan', province: 'MB', size: 'small', scheduled: true, status: 'future', gps: { lat: 55.7492, lng: -101.266 } },
  { code: 'YRS', icao: 'CYRS', name: 'Red Sucker Lake', province: 'MB', size: 'small', scheduled: true, status: 'future', gps: { lat: 54.1672, lng: -93.5572 } },
  { code: 'ZTM', icao: 'CZTM', name: 'Shamattawa', province: 'MB', size: 'small', scheduled: true, status: 'future', gps: { lat: 55.8636, lng: -92.0811 } },
  { code: 'XSI', icao: 'CZSN', name: 'South Indian Lake', province: 'MB', size: 'small', scheduled: true, status: 'future', gps: { lat: 56.7928, lng: -98.9072 } },
  { code: 'YST', icao: 'CYST', name: 'St. Theresa Point', province: 'MB', size: 'small', scheduled: true, status: 'future', gps: { lat: 53.8453, lng: -94.852 } },
  { code: 'ZJN', icao: 'CZJN', name: 'Swan River', province: 'MB', size: 'medium', status: 'future', gps: { lat: 52.1206, lng: -101.236 } },
  { code: 'XTL', icao: 'CYBQ', name: 'Tadoule Lake', province: 'MB', size: 'small', scheduled: true, status: 'future', gps: { lat: 58.7063, lng: -98.5111 } },
  { code: 'YQD', icao: 'CYQD', name: 'The Pas', province: 'MB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 53.9714, lng: -101.091 } },
  { code: 'YTD', icao: 'CZLQ', name: 'Thicket Portage', province: 'MB', size: 'medium', status: 'future', gps: { lat: 55.3189, lng: -97.7078 } },
  { code: 'YTH', icao: 'CYTH', name: 'Thompson', province: 'MB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 55.8011, lng: -97.8642 } },
  { code: 'YWG', icao: 'CYWG', name: 'Winnipeg', province: 'MB', size: 'large', scheduled: true, status: 'future', gps: { lat: 49.91, lng: -97.2399 } },
  { code: 'CYAV', icao: 'CYAV', name: 'Winnipeg/Saint Andrews', province: 'MB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 50.0564, lng: -97.0325 } },
  { code: 'ZAC', icao: 'CZAC', name: 'York Landing', province: 'MB', size: 'small', status: 'future', gps: { lat: 56.0894, lng: -96.0892 } },

  /* ── SK · 24 aéroports ─────────────────────────────── */
  { code: 'YVT', icao: 'CYVT', name: 'Buffalo Narrows', province: 'SK', size: 'small', status: 'future', gps: { lat: 55.8419, lng: -108.418 } },
  { code: 'XCL', icao: 'CJS3', name: 'Cluff Lake', province: 'SK', size: 'small', status: 'future', gps: { lat: 58.3911, lng: -109.516 } },
  { code: 'YKC', icao: 'CYKC', name: 'Collins Bay', province: 'SK', size: 'small', status: 'future', gps: { lat: 58.2361, lng: -103.678 } },
  { code: 'YEN', icao: 'CYEN', name: 'Estevan', province: 'SK', size: 'medium', status: 'future', gps: { lat: 49.2103, lng: -102.966 } },
  { code: 'ZFD', icao: 'CZFD', name: 'Fond-du-Lac', province: 'SK', size: 'small', scheduled: true, status: 'future', gps: { lat: 59.3344, lng: -107.182 } },
  { code: 'YDJ', icao: 'CJL2', name: 'Hatchet Lake', province: 'SK', size: 'small', status: 'future', gps: { lat: 58.6625, lng: -103.538 } },
  { code: 'YHB', icao: 'CYHB', name: 'Hudson Bay', province: 'SK', size: 'small', status: 'future', gps: { lat: 52.8167, lng: -102.311 } },
  { code: 'YKJ', icao: 'CYKJ', name: 'Key Lake', province: 'SK', size: 'medium', status: 'future', gps: { lat: 57.2561, lng: -105.618 } },
  { code: 'YKY', icao: 'CYKY', name: 'Kindersley', province: 'SK', size: 'medium', status: 'future', gps: { lat: 51.5175, lng: -109.181 } },
  { code: 'YVC', icao: 'CYVC', name: 'La Ronge', province: 'SK', size: 'medium', scheduled: true, status: 'future', gps: { lat: 55.1514, lng: -105.262 } },
  { code: 'YLJ', icao: 'CYLJ', name: 'Meadow Lake', province: 'SK', size: 'medium', status: 'future', gps: { lat: 54.1253, lng: -108.523 } },
  { code: 'YMJ', icao: 'CYMJ', name: 'Moose Jaw', province: 'SK', size: 'medium', status: 'future', gps: { lat: 50.3303, lng: -105.559 } },
  { code: 'YQW', icao: 'CYQW', name: 'North Battleford', province: 'SK', size: 'medium', status: 'future', gps: { lat: 52.7694, lng: -108.2437 } },
  { code: 'ZPO', icao: 'CZPO', name: 'Pinehouse Lake', province: 'SK', size: 'small', status: 'future', gps: { lat: 55.5281, lng: -106.582 } },
  { code: 'YNL', icao: 'CYNL', name: 'Points North Landing', province: 'SK', size: 'medium', scheduled: true, status: 'future', gps: { lat: 58.2767, lng: -104.082 } },
  { code: 'YPA', icao: 'CYPA', name: 'Prince Albert', province: 'SK', size: 'medium', scheduled: true, status: 'future', gps: { lat: 53.2142, lng: -105.673 } },
  { code: 'YQR', icao: 'CYQR', name: 'Regina', province: 'SK', size: 'medium', scheduled: true, status: 'future', gps: { lat: 50.4319, lng: -104.6609 } },
  { code: 'YXE', icao: 'CYXE', name: 'Saskatoon', province: 'SK', size: 'large', scheduled: true, status: 'future', gps: { lat: 52.1707, lng: -106.7008 } },
  { code: 'YSF', icao: 'CYSF', name: 'Stony Rapids', province: 'SK', size: 'medium', scheduled: true, status: 'future', gps: { lat: 59.2503, lng: -105.841 } },
  { code: 'YYN', icao: 'CYYN', name: 'Swift Current', province: 'SK', size: 'medium', status: 'future', gps: { lat: 50.2919, lng: -107.691 } },
  { code: 'YTT', icao: 'CJY3', name: 'Tisdale', province: 'SK', size: 'small', status: 'future', gps: { lat: 52.8367, lng: -104.067 } },
  { code: 'YBE', icao: 'CYBE', name: 'Uranium City', province: 'SK', size: 'small', scheduled: true, status: 'future', gps: { lat: 59.5614, lng: -108.481 } },
  { code: 'ZWL', icao: 'CZWL', name: 'Wollaston Lake', province: 'SK', size: 'small', scheduled: true, status: 'future', gps: { lat: 58.1069, lng: -103.172 } },
  { code: 'YQV', icao: 'CYQV', name: 'Yorkton', province: 'SK', size: 'medium', status: 'future', gps: { lat: 51.2647, lng: -102.462 } },

  /* ── AB · 40 aéroports ─────────────────────────────── */
  { code: 'JHL', icao: 'CAL4', name: 'Albian Village', province: 'AB', size: 'small', status: 'future', gps: { lat: 57.2239, lng: -111.419 } },
  { code: 'YBA', icao: 'CYBA', name: 'Banff', province: 'AB', size: 'small', status: 'future', gps: { lat: 51.2082, lng: -115.5406 } },
  { code: 'YBY', icao: 'CYBF', name: 'Bonnyville', province: 'AB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 54.3042, lng: -110.744 } },
  { code: 'YYC', icao: 'CYYC', name: 'Calgary', province: 'AB', size: 'large', scheduled: true, status: 'future', gps: { lat: 51.1188, lng: -114.0099 } },
  { code: 'TIL', icao: 'CFQ4', name: 'Cheadle', province: 'AB', size: 'small', status: 'future', gps: { lat: 51.0575, lng: -113.624 } },
  { code: 'YOD', icao: 'CYOD', name: 'Cold Lake', province: 'AB', size: 'medium', status: 'future', gps: { lat: 54.405, lng: -110.279 } },
  { code: 'CFM', icao: 'CET2', name: 'Conklin', province: 'AB', size: 'small', status: 'future', gps: { lat: 55.6953, lng: -111.279 } },
  { code: 'YCT', icao: 'CYCT', name: 'Coronation', province: 'AB', size: 'small', status: 'future', gps: { lat: 52.075, lng: -111.445 } },
  { code: 'YYM', icao: 'CYYM', name: 'Cowley', province: 'AB', size: 'small', status: 'future', gps: { lat: 49.6364, lng: -114.094 } },
  { code: 'YOE', icao: 'CFM4', name: 'Donnelly', province: 'AB', size: 'small', status: 'future', gps: { lat: 55.7094, lng: -117.094 } },
  { code: 'YDC', icao: 'CER3', name: 'Drayton Valley', province: 'AB', size: 'small', status: 'future', gps: { lat: 53.2658, lng: -114.96 } },
  { code: 'CA-1291', name: 'Edmonton', province: 'AB', size: 'large', scheduled: true, status: 'future', gps: { lat: 53.3097, lng: -113.58 } },
  { code: 'CA-1292', name: 'Edmonton', province: 'AB', size: 'large', scheduled: true, status: 'future', gps: { lat: 50.3417, lng: -106.6992 } },
  { code: 'YEG', icao: 'CYEG', name: 'Edmonton', province: 'AB', size: 'large', scheduled: true, status: 'future', gps: { lat: 53.3097, lng: -113.58 } },
  { code: 'YET', icao: 'CYET', name: 'Edson', province: 'AB', size: 'medium', status: 'future', gps: { lat: 53.5789, lng: -116.465 } },
  { code: 'ZFW', icao: 'CEB5', name: 'Fairview', province: 'AB', size: 'small', status: 'future', gps: { lat: 56.0814, lng: -118.435 } },
  { code: 'YPY', icao: 'CYPY', name: 'Fort Chipewyan', province: 'AB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 58.7672, lng: -111.117 } },
  { code: 'HZP', icao: 'CYNR', name: 'Fort Mackay', province: 'AB', size: 'small', status: 'future', gps: { lat: 57.3817, lng: -111.701 } },
  { code: 'NML', icao: 'CER4', name: 'Fort McMurray', province: 'AB', size: 'small', status: 'future', gps: { lat: 57.0556, lng: -111.574 } },
  { code: 'YMM', icao: 'CYMM', name: 'Fort McMurray', province: 'AB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 56.6533, lng: -111.222 } },
  { code: 'YQU', icao: 'CYQU', name: 'Grande Prairie', province: 'AB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 55.1797, lng: -118.885 } },
  { code: 'YOJ', icao: 'CYOJ', name: 'High Level', province: 'AB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 58.6214, lng: -117.165 } },
  { code: 'ZHP', icao: 'CZHP', name: 'High Prairie', province: 'AB', size: 'small', status: 'future', gps: { lat: 55.3936, lng: -116.475 } },
  { code: 'YJP', icao: 'CEC4', name: 'Hinton', province: 'AB', size: 'small', status: 'future', gps: { lat: 53.3192, lng: -117.753 } },
  { code: 'YJA', icao: 'CYJA', name: 'Jasper', province: 'AB', size: 'small', status: 'future', gps: { lat: 52.9964, lng: -118.0602 } },
  { code: 'KFM', icao: 'CRL4', name: 'Kirby Lake', province: 'AB', size: 'small', status: 'future', gps: { lat: 55.3556, lng: -110.637 } },
  { code: 'YLB', icao: 'CYLB', name: 'Lac La Biche', province: 'AB', size: 'small', status: 'future', gps: { lat: 54.7703, lng: -112.032 } },
  { code: 'YQL', icao: 'CYQL', name: 'Lethbridge', province: 'AB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 49.6303, lng: -112.8 } },
  { code: 'YLL', icao: 'CYLL', name: 'Lloydminster', province: 'AB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 53.3092, lng: -110.073 } },
  { code: 'YXH', icao: 'CYXH', name: 'Medicine Hat', province: 'AB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 50.0189, lng: -110.721 } },
  { code: 'YPE', icao: 'CYPE', name: 'Peace River', province: 'AB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 56.2269, lng: -117.447 } },
  { code: 'WPC', icao: 'CZPC', name: 'Pincher Creek', province: 'AB', size: 'medium', status: 'future', gps: { lat: 49.5204, lng: -113.997 } },
  { code: 'PFM', name: 'Primrose', province: 'AB', size: 'small', status: 'future', gps: { lat: 55.39, lng: -111.1198 } },
  { code: 'YOP', icao: 'CYOP', name: 'Rainbow Lake', province: 'AB', size: 'medium', status: 'future', gps: { lat: 58.4914, lng: -119.408 } },
  { code: 'YRM', icao: 'CYRM', name: 'Rocky Mountain House', province: 'AB', size: 'small', status: 'future', gps: { lat: 52.4297, lng: -114.904 } },
  { code: 'YZH', icao: 'CYZH', name: 'Slave Lake', province: 'AB', size: 'medium', status: 'future', gps: { lat: 55.2929, lng: -114.7773 } },
  { code: 'YQF', icao: 'CYQF', name: 'Springbrook', province: 'AB', size: 'medium', status: 'future', gps: { lat: 52.1822, lng: -113.894 } },
  { code: 'YFI', icao: 'CFG6', name: 'Suncor Energy Site', province: 'AB', size: 'small', status: 'future', gps: { lat: 57.2758, lng: -110.9767 } },
  { code: 'YVG', icao: 'CYVG', name: 'Vermilion', province: 'AB', size: 'small', status: 'future', gps: { lat: 53.3577, lng: -110.8274 } },
  { code: 'YZU', icao: 'CYZU', name: 'Whitecourt', province: 'AB', size: 'medium', scheduled: true, status: 'future', gps: { lat: 54.1439, lng: -115.787 } },

  /* ── BC · 69 aéroports ─────────────────────────────── */
  { code: 'ZMH', icao: 'CZML', name: '108 Mile', province: 'BC', size: 'small', status: 'future', gps: { lat: 51.7361, lng: -121.333 } },
  { code: 'YXX', icao: 'CYXX', name: 'Abbotsford', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 49.0253, lng: -122.361 } },
  { code: 'YAL', icao: 'CYAL', name: 'Alert Bay', province: 'BC', size: 'small', scheduled: true, status: 'future', gps: { lat: 50.5822, lng: -126.916 } },
  { code: 'YAA', icao: 'CAJ4', name: 'Anahim Lake', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 52.4515, lng: -125.3038 } },
  { code: 'CYSQ', icao: 'CYSQ', name: 'Atlin', province: 'BC', size: 'small', scheduled: true, status: 'future', gps: { lat: 59.5783, lng: -133.6689 } },
  { code: 'ZEL', icao: 'CBBC', name: 'Bella Bella', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 52.185, lng: -128.157 } },
  { code: 'QBC', icao: 'CYBD', name: 'Bella Coola', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 52.3875, lng: -126.596 } },
  { code: 'YRR', name: 'Big Bay', province: 'BC', size: 'small', status: 'future', gps: { lat: 50.4094, lng: -125.1316 } },
  { code: 'YBO', icao: 'CBW4', name: 'Bob Quinn Lake', province: 'BC', size: 'small', status: 'future', gps: { lat: 56.9667, lng: -130.25 } },
  { code: 'YPZ', icao: 'CYPZ', name: 'Burns Lake', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 54.3764, lng: -125.951 } },
  { code: 'YZA', icao: 'CAZ5', name: 'Cache Creek', province: 'BC', size: 'medium', status: 'future', gps: { lat: 50.7753, lng: -121.3213 } },
  { code: 'YBL', icao: 'CYBL', name: 'Campbell River', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 49.9508, lng: -125.271 } },
  { code: 'YCG', icao: 'CYCG', name: 'Castlegar', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 49.2964, lng: -117.632 } },
  { code: 'YCQ', icao: 'CYCQ', name: 'Chetwynd', province: 'BC', size: 'medium', status: 'future', gps: { lat: 55.6872, lng: -121.627 } },
  { code: 'CJH', icao: 'CAG3', name: 'Chilko Lake', province: 'BC', size: 'small', status: 'future', gps: { lat: 51.6258, lng: -124.1445 } },
  { code: 'YCW', icao: 'CYCW', name: 'Chilliwack', province: 'BC', size: 'small', status: 'future', gps: { lat: 49.1532, lng: -121.9393 } },
  { code: 'YQQ', icao: 'CYQQ', name: 'Comox', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 49.7108, lng: -124.887 } },
  { code: 'YCA', icao: 'CAH3', name: 'Courtenay', province: 'BC', size: 'small', status: 'future', gps: { lat: 49.6792, lng: -124.9806 } },
  { code: 'YXC', icao: 'CYXC', name: 'Cranbrook', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 49.6108, lng: -115.782 } },
  { code: 'CFQ', icao: 'CAJ3', name: 'Creston', province: 'BC', size: 'small', status: 'future', gps: { lat: 49.0369, lng: -116.498 } },
  { code: 'YDQ', icao: 'CYDQ', name: 'Dawson Creek', province: 'BC', size: 'medium', status: 'future', gps: { lat: 55.7412, lng: -120.1833 } },
  { code: 'YDL', icao: 'CYDL', name: 'Dease Lake', province: 'BC', size: 'small', scheduled: true, status: 'future', gps: { lat: 58.4222, lng: -130.032 } },
  { code: 'YDT', icao: 'CZBB', name: 'Delta', province: 'BC', size: 'medium', status: 'future', gps: { lat: 49.0743, lng: -123.0069 } },
  { code: 'DGF', icao: 'CAL3', name: 'Douglas Lake', province: 'BC', size: 'small', status: 'future', gps: { lat: 50.1655, lng: -120.1713 } },
  { code: 'DUQ', icao: 'CAM3', name: 'Duncan', province: 'BC', size: 'small', status: 'future', gps: { lat: 48.7545, lng: -123.7097 } },
  { code: 'YCZ', icao: 'CYCZ', name: 'Fairmont Hot Springs', province: 'BC', size: 'small', status: 'future', gps: { lat: 50.3311, lng: -115.8737 } },
  { code: 'YYE', icao: 'CYYE', name: 'Fort Nelson', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 58.8364, lng: -122.597 } },
  { code: 'YXJ', icao: 'CYXJ', name: 'Fort Saint John', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 56.2381, lng: -120.74 } },
  { code: 'CAJ9', icao: 'CAJ9', name: 'Fort Ware', province: 'BC', size: 'small', scheduled: true, status: 'future', gps: { lat: 57.4279, lng: -125.6482 } },
  { code: 'ZGF', icao: 'CZGF', name: 'Grand Forks', province: 'BC', size: 'medium', status: 'future', gps: { lat: 49.0156, lng: -118.431 } },
  { code: 'YHE', icao: 'CYHE', name: 'Hope', province: 'BC', size: 'small', status: 'future', gps: { lat: 49.3689, lng: -121.495 } },
  { code: 'YNH', icao: 'CYNH', name: 'Hudson\'s Hope', province: 'BC', size: 'small', status: 'future', gps: { lat: 56.0351, lng: -121.9783 } },
  { code: 'YKA', icao: 'CYKA', name: 'Kamloops', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 50.703, lng: -120.4486 } },
  { code: 'YLW', icao: 'CYLW', name: 'Kelowna', province: 'BC', size: 'large', scheduled: true, status: 'future', gps: { lat: 49.9561, lng: -119.378 } },
  { code: 'YRD', name: 'Kimsquit Valley', province: 'BC', size: 'small', status: 'future', gps: { lat: 52.8237, lng: -126.965 } },
  { code: 'YLY', icao: 'CYNJ', name: 'Langley', province: 'BC', size: 'medium', status: 'future', gps: { lat: 49.1008, lng: -122.631 } },
  { code: 'CYZY', icao: 'CYZY', name: 'Mackenzie', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 55.2978, lng: -123.1339 } },
  { code: 'ZMT', icao: 'CZMT', name: 'Masset', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 54.0275, lng: -132.125 } },
  { code: 'YMB', icao: 'CAD5', name: 'Merritt', province: 'BC', size: 'small', status: 'future', gps: { lat: 50.1225, lng: -120.7454 } },
  { code: 'YCD', icao: 'CYCD', name: 'Nanaimo', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 49.055, lng: -123.8699 } },
  { code: 'CBA9', icao: 'CBA9', name: 'Ospika', province: 'BC', size: 'small', scheduled: true, status: 'future', gps: { lat: 56.271, lng: -124.0633 } },
  { code: 'YYF', icao: 'CYYF', name: 'Penticton', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 49.4631, lng: -119.602 } },
  { code: 'CYPK', icao: 'CYPK', name: 'Pitt Meadows', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 49.2149, lng: -122.7093 } },
  { code: 'YPB', icao: 'CBS8', name: 'Port Alberni', province: 'BC', size: 'small', status: 'future', gps: { lat: 49.3219, lng: -124.931 } },
  { code: 'YZT', icao: 'CYZT', name: 'Port Hardy', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 50.6806, lng: -127.367 } },
  { code: 'YMP', icao: 'CAT5', name: 'Port McNeill', province: 'BC', size: 'small', scheduled: true, status: 'future', gps: { lat: 50.5735, lng: -127.0277 } },
  { code: 'YPW', icao: 'CYPW', name: 'Powell River', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 49.8342, lng: -124.5 } },
  { code: 'YXS', icao: 'CYXS', name: 'Prince George', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 53.8843, lng: -122.6666 } },
  { code: 'YPR', icao: 'CYPR', name: 'Prince Rupert', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 54.2861, lng: -130.445 } },
  { code: 'XQU', icao: 'CAT4', name: 'Qualicum Beach', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 49.3375, lng: -124.3931 } },
  { code: 'YQZ', icao: 'CYQZ', name: 'Quesnel', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 53.0261, lng: -122.51 } },
  { code: 'YRV', icao: 'CYRV', name: 'Revelstoke', province: 'BC', size: 'medium', status: 'future', gps: { lat: 50.9622, lng: -118.1843 } },
  { code: 'YSN', icao: 'CZAM', name: 'Salmon Arm', province: 'BC', size: 'medium', status: 'future', gps: { lat: 50.6828, lng: -119.229 } },
  { code: 'YZP', icao: 'CYZP', name: 'Sandspit', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 53.2543, lng: -131.814 } },
  { code: 'YHS', icao: 'CAP3', name: 'Sechelt', province: 'BC', size: 'small', status: 'future', gps: { lat: 49.4606, lng: -123.719 } },
  { code: 'YYD', icao: 'CYYD', name: 'Smithers', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 54.8247, lng: -127.183 } },
  { code: 'YSE', icao: 'CYSE', name: 'Squamish', province: 'BC', size: 'small', status: 'future', gps: { lat: 49.7817, lng: -123.162 } },
  { code: 'ZST', icao: 'CZST', name: 'Stewart', province: 'BC', size: 'medium', status: 'future', gps: { lat: 55.9354, lng: -129.9824 } },
  { code: 'CRHA', icao: 'CRHA', name: 'Streatham', province: 'BC', size: 'small', scheduled: true, status: 'future', gps: { lat: 53.8226, lng: -126.173 } },
  { code: 'YXT', icao: 'CYXT', name: 'Terrace', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 54.4685, lng: -128.576 } },
  { code: 'YGB', icao: 'CYGB', name: 'Texada', province: 'BC', size: 'small', status: 'future', gps: { lat: 49.6943, lng: -124.5181 } },
  { code: 'YAZ', icao: 'CYAZ', name: 'Tofino', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 49.0798, lng: -125.7756 } },
  { code: 'YZZ', icao: 'CAD4', name: 'Trail', province: 'BC', size: 'small', scheduled: true, status: 'future', gps: { lat: 49.0556, lng: -117.609 } },
  { code: 'CBN9', icao: 'CBN9', name: 'Tsay Keh', province: 'BC', size: 'small', scheduled: true, status: 'future', gps: { lat: 56.9061, lng: -124.965 } },
  { code: 'TUX', icao: 'CBX7', name: 'Tumbler Ridge', province: 'BC', size: 'small', status: 'future', gps: { lat: 55.025, lng: -120.935 } },
  { code: 'YVR', icao: 'CYVR', name: 'Vancouver', province: 'BC', size: 'large', scheduled: true, status: 'future', gps: { lat: 49.1939, lng: -123.184 } },
  { code: 'YVE', icao: 'CYVK', name: 'Vernon', province: 'BC', size: 'medium', status: 'future', gps: { lat: 50.2462, lng: -119.331 } },
  { code: 'YYJ', icao: 'CYYJ', name: 'Victoria', province: 'BC', size: 'large', scheduled: true, status: 'future', gps: { lat: 48.6472, lng: -123.4278 } },
  { code: 'YWL', icao: 'CYWL', name: 'Williams Lake', province: 'BC', size: 'medium', scheduled: true, status: 'future', gps: { lat: 52.1831, lng: -122.054 } },

  /* ── YT · 12 aéroports ─────────────────────────────── */
  { code: 'YXQ', icao: 'CYXQ', name: 'Beaver Creek', province: 'YT', size: 'medium', status: 'future', gps: { lat: 62.4103, lng: -140.867 } },
  { code: 'YDB', icao: 'CYDB', name: 'Burwash Landing', province: 'YT', size: 'medium', status: 'future', gps: { lat: 61.3711, lng: -139.041 } },
  { code: 'YDA', icao: 'CYDA', name: 'Dawson City', province: 'YT', size: 'medium', scheduled: true, status: 'future', gps: { lat: 64.0431, lng: -139.128 } },
  { code: 'ZFA', icao: 'CZFA', name: 'Faro', province: 'YT', size: 'medium', status: 'future', gps: { lat: 62.2075, lng: -133.376 } },
  { code: 'YHT', icao: 'CYHT', name: 'Haines Junction', province: 'YT', size: 'medium', status: 'future', gps: { lat: 60.7892, lng: -137.546 } },
  { code: 'XMP', icao: 'CFC4', name: 'Macmillan Pass', province: 'YT', size: 'small', status: 'future', gps: { lat: 63.1811, lng: -130.202 } },
  { code: 'YMA', icao: 'CYMA', name: 'Mayo', province: 'YT', size: 'medium', status: 'future', gps: { lat: 63.6164, lng: -135.868 } },
  { code: 'YOC', icao: 'CYOC', name: 'Old Crow', province: 'YT', size: 'small', scheduled: true, status: 'future', gps: { lat: 67.5706, lng: -139.839 } },
  { code: 'XRR', icao: 'CYDM', name: 'Ross River', province: 'YT', size: 'medium', status: 'future', gps: { lat: 61.9706, lng: -132.423 } },
  { code: 'YZW', icao: 'CYZW', name: 'Teslin', province: 'YT', size: 'medium', status: 'future', gps: { lat: 60.1728, lng: -132.743 } },
  { code: 'YQH', icao: 'CYQH', name: 'Watson Lake', province: 'YT', size: 'medium', scheduled: true, status: 'future', gps: { lat: 60.1168, lng: -128.822 } },
  { code: 'YXY', icao: 'CYXY', name: 'Whitehorse', province: 'YT', size: 'medium', scheduled: true, status: 'future', gps: { lat: 60.7085, lng: -135.0657 } },

  /* ── NT · 32 aéroports ─────────────────────────────── */
  { code: 'LAK', icao: 'CYKD', name: 'Aklavik', province: 'NT', size: 'small', scheduled: true, status: 'future', gps: { lat: 68.2233, lng: -135.006 } },
  { code: 'YCK', icao: 'CYVL', name: 'Colville Lake', province: 'NT', size: 'small', scheduled: true, status: 'future', gps: { lat: 67.0202, lng: -126.1284 } },
  { code: 'YWJ', icao: 'CYWJ', name: 'Déline', province: 'NT', size: 'small', scheduled: true, status: 'future', gps: { lat: 65.2111, lng: -123.436 } },
  { code: 'DVK', icao: 'CDK2', name: 'Diavik', province: 'NT', size: 'small', status: 'future', gps: { lat: 64.5114, lng: -110.289 } },
  { code: 'YOA', icao: 'CYOA', name: 'Ekati', province: 'NT', size: 'medium', status: 'future', gps: { lat: 64.6989, lng: -110.615 } },
  { code: 'YGH', icao: 'CYGH', name: 'Fort Good Hope', province: 'NT', size: 'small', scheduled: true, status: 'future', gps: { lat: 66.2407, lng: -128.6478 } },
  { code: 'YJF', icao: 'CYJF', name: 'Fort Liard', province: 'NT', size: 'medium', status: 'future', gps: { lat: 60.2358, lng: -123.469 } },
  { code: 'ZFM', icao: 'CZFM', name: 'Fort Mcpherson', province: 'NT', size: 'small', scheduled: true, status: 'future', gps: { lat: 67.407, lng: -134.8602 } },
  { code: 'YFR', icao: 'CYFR', name: 'Fort Resolution', province: 'NT', size: 'medium', status: 'future', gps: { lat: 61.1808, lng: -113.69 } },
  { code: 'YFS', icao: 'CYFS', name: 'Fort Simpson', province: 'NT', size: 'medium', scheduled: true, status: 'future', gps: { lat: 61.7602, lng: -121.237 } },
  { code: 'YSM', icao: 'CYSM', name: 'Fort Smith', province: 'NT', size: 'medium', scheduled: true, status: 'future', gps: { lat: 60.0203, lng: -111.962 } },
  { code: 'YRA', icao: 'CYRA', name: 'Gamètì', province: 'NT', size: 'small', scheduled: true, status: 'future', gps: { lat: 64.1161, lng: -117.31 } },
  { code: 'DAS', icao: 'CFF4', name: 'Great Bear Lake', province: 'NT', size: 'small', status: 'future', gps: { lat: 66.7031, lng: -119.7168 } },
  { code: 'YHY', icao: 'CYHY', name: 'Hay River', province: 'NT', size: 'medium', scheduled: true, status: 'future', gps: { lat: 60.8397, lng: -115.783 } },
  { code: 'YEV', icao: 'CYEV', name: 'Inuvik', province: 'NT', size: 'medium', scheduled: true, status: 'future', gps: { lat: 68.3042, lng: -133.483 } },
  { code: 'YDU', icao: 'CJL8', name: 'Kasba Lake', province: 'NT', size: 'small', status: 'future', gps: { lat: 60.2919, lng: -102.502 } },
  { code: 'GHK', icao: 'CGK2', name: 'Kennedy Lake', province: 'NT', size: 'small', status: 'future', gps: { lat: 63.4352, lng: -109.1448 } },
  { code: 'YSG', icao: 'CYLK', name: 'Lutselk\'e', province: 'NT', size: 'small', scheduled: true, status: 'future', gps: { lat: 62.4178, lng: -110.6828 } },
  { code: 'YVQ', icao: 'CYVQ', name: 'Norman Wells', province: 'NT', size: 'medium', scheduled: true, status: 'future', gps: { lat: 65.2816, lng: -126.798 } },
  { code: 'YDW', icao: 'CKV4', name: 'Obre Lake', province: 'NT', size: 'small', status: 'future', gps: { lat: 60.3157, lng: -103.1313 } },
  { code: 'YPC', icao: 'CYPC', name: 'Paulatuk', province: 'NT', size: 'small', scheduled: true, status: 'future', gps: { lat: 69.3608, lng: -124.0755 } },
  { code: 'YSY', icao: 'CYSY', name: 'Sachs Harbour', province: 'NT', size: 'small', scheduled: true, status: 'future', gps: { lat: 71.9939, lng: -125.243 } },
  { code: 'YNX', icao: 'CSK6', name: 'Snap Lake Mine', province: 'NT', size: 'small', status: 'future', gps: { lat: 63.5936, lng: -110.906 } },
  { code: 'GSL', icao: 'CFA7', name: 'Taltheilei Narrows', province: 'NT', size: 'small', status: 'future', gps: { lat: 62.5981, lng: -111.543 } },
  { code: 'YUB', icao: 'CYUB', name: 'Tuktoyaktuk', province: 'NT', size: 'small', status: 'future', gps: { lat: 69.4333, lng: -133.026 } },
  { code: 'ZFN', icao: 'CZFN', name: 'Tulita', province: 'NT', size: 'small', scheduled: true, status: 'future', gps: { lat: 64.9095, lng: -125.5703 } },
  { code: 'TNS', icao: 'CBX5', name: 'Tungsten', province: 'NT', size: 'small', status: 'future', gps: { lat: 61.9569, lng: -128.203 } },
  { code: 'YHI', icao: 'CYHI', name: 'Ulukhaktok', province: 'NT', size: 'small', scheduled: true, status: 'future', gps: { lat: 70.7628, lng: -117.806 } },
  { code: 'YFJ', icao: 'CYWE', name: 'Wekweètì', province: 'NT', size: 'small', scheduled: true, status: 'future', gps: { lat: 64.1908, lng: -114.077 } },
  { code: 'YLE', icao: 'CEM3', name: 'Whatì', province: 'NT', size: 'small', scheduled: true, status: 'future', gps: { lat: 63.1317, lng: -117.246 } },
  { code: 'YWY', icao: 'CYWY', name: 'Wrigley', province: 'NT', size: 'medium', status: 'future', gps: { lat: 63.2094, lng: -123.437 } },
  { code: 'YZF', icao: 'CYZF', name: 'Yellowknife', province: 'NT', size: 'medium', scheduled: true, status: 'future', gps: { lat: 62.4628, lng: -114.44 } },

  /* ── NU · 30 aéroports ─────────────────────────────── */
  { code: 'YLT', icao: 'CYLT', name: 'Alert', province: 'NU', size: 'medium', status: 'future', gps: { lat: 82.5173, lng: -62.283 } },
  { code: 'YAB', icao: 'CYAB', name: 'Arctic Bay', province: 'NU', size: 'small', scheduled: true, status: 'future', gps: { lat: 73.0061, lng: -85.0462 } },
  { code: 'YEK', icao: 'CYEK', name: 'Arviat', province: 'NU', size: 'small', scheduled: true, status: 'future', gps: { lat: 61.0942, lng: -94.0708 } },
  { code: 'YBK', icao: 'CYBK', name: 'Baker Lake', province: 'NU', size: 'medium', scheduled: true, status: 'future', gps: { lat: 64.2989, lng: -96.0778 } },
  { code: 'YCB', icao: 'CYCB', name: 'Cambridge Bay', province: 'NU', size: 'medium', scheduled: true, status: 'future', gps: { lat: 69.1081, lng: -105.138 } },
  { code: 'YCS', icao: 'CYCS', name: 'Chesterfield Inlet', province: 'NU', size: 'small', scheduled: true, status: 'future', gps: { lat: 63.3469, lng: -90.7311 } },
  { code: 'YCY', icao: 'CYCY', name: 'Clyde River', province: 'NU', size: 'small', scheduled: true, status: 'future', gps: { lat: 70.4861, lng: -68.5167 } },
  { code: 'YZS', icao: 'CYZS', name: 'Coral Harbour', province: 'NU', size: 'medium', scheduled: true, status: 'future', gps: { lat: 64.1933, lng: -83.3594 } },
  { code: 'YEU', icao: 'CYEU', name: 'Eureka', province: 'NU', size: 'small', status: 'future', gps: { lat: 79.9947, lng: -85.8142 } },
  { code: 'YHK', icao: 'CYHK', name: 'Gjoa Haven', province: 'NU', size: 'small', scheduled: true, status: 'future', gps: { lat: 68.6356, lng: -95.8497 } },
  { code: 'YGZ', icao: 'CYGZ', name: 'Grise Fiord', province: 'NU', size: 'small', scheduled: true, status: 'future', gps: { lat: 76.4258, lng: -82.9086 } },
  { code: 'JOJ', icao: 'CDL7', name: 'Hope Bay', province: 'NU', size: 'small', status: 'future', gps: { lat: 68.1253, lng: -106.5853 } },
  { code: 'UZM', name: 'Hope Bay', province: 'NU', size: 'small', status: 'future', gps: { lat: 68.156, lng: -106.618 } },
  { code: 'YGT', icao: 'CYGT', name: 'Igloolik', province: 'NU', size: 'small', scheduled: true, status: 'future', gps: { lat: 69.3647, lng: -81.8161 } },
  { code: 'YFB', icao: 'CYFB', name: 'Iqaluit', province: 'NU', size: 'medium', scheduled: true, status: 'future', gps: { lat: 63.7564, lng: -68.5558 } },
  { code: 'YLC', icao: 'CYLC', name: 'Kimmirut', province: 'NU', size: 'small', scheduled: true, status: 'future', gps: { lat: 62.8483, lng: -69.8779 } },
  { code: 'YTE', icao: 'CYTE', name: 'Kinngait', province: 'NU', size: 'small', scheduled: true, status: 'future', gps: { lat: 64.23, lng: -76.5267 } },
  { code: 'YBB', icao: 'CYBB', name: 'Kugaaruk', province: 'NU', size: 'small', scheduled: true, status: 'future', gps: { lat: 68.5357, lng: -89.8055 } },
  { code: 'YCO', icao: 'CYCO', name: 'Kugluktuk', province: 'NU', size: 'small', scheduled: true, status: 'future', gps: { lat: 67.8164, lng: -115.1431 } },
  { code: 'YMV', name: 'Mary River', province: 'NU', size: 'small', status: 'future', gps: { lat: 71.3242, lng: -79.3569 } },
  { code: 'YXP', icao: 'CYXP', name: 'Pangnirtung', province: 'NU', size: 'small', scheduled: true, status: 'future', gps: { lat: 66.1449, lng: -65.7136 } },
  { code: 'YIO', icao: 'CYIO', name: 'Pond Inlet', province: 'NU', size: 'small', scheduled: true, status: 'future', gps: { lat: 72.6895, lng: -77.9689 } },
  { code: 'YVM', icao: 'CYVM', name: 'Qikiqtarjuaq', province: 'NU', size: 'small', scheduled: true, status: 'future', gps: { lat: 67.5466, lng: -64.0314 } },
  { code: 'YRT', icao: 'CYRT', name: 'Rankin Inlet', province: 'NU', size: 'medium', scheduled: true, status: 'future', gps: { lat: 62.8114, lng: -92.1158 } },
  { code: 'YUT', icao: 'CYUT', name: 'Repulse Bay', province: 'NU', size: 'small', scheduled: true, status: 'future', gps: { lat: 66.521, lng: -86.2252 } },
  { code: 'YRB', icao: 'CYRB', name: 'Resolute Bay', province: 'NU', size: 'medium', scheduled: true, status: 'future', gps: { lat: 74.7169, lng: -94.9694 } },
  { code: 'YSK', icao: 'CYSK', name: 'Sanikiluaq', province: 'NU', size: 'small', scheduled: true, status: 'future', gps: { lat: 56.5369, lng: -79.2502 } },
  { code: 'YUX', icao: 'CYUX', name: 'Sanirajak', province: 'NU', size: 'medium', scheduled: true, status: 'future', gps: { lat: 68.7761, lng: -81.2425 } },
  { code: 'YYH', icao: 'CYYH', name: 'Taloyoak', province: 'NU', size: 'small', scheduled: true, status: 'future', gps: { lat: 69.5467, lng: -93.5767 } },
  { code: 'YXN', icao: 'CYXN', name: 'Whale Cove', province: 'NU', size: 'small', scheduled: true, status: 'future', gps: { lat: 62.24, lng: -92.5981 } },
]
